### ISSUE TITLE
Reach parity with other TI tokenization tools

### ISSUE THREAD

**Issue by rpitasky** [cqb13/ti-tools#2]
Hey! Primary maintainer of https://github.com/TI-Toolkit/tokens & avid Rust user here; I love seeing projects like this. Thank you for using our data- we're trying to contain the further proliferation of new token formats!

---

Turning text into tokens is surprisingly thorny. "You can't parse a dumb language with a dumb parser" is my name for this problem. I recently wrote a primer [in a Cemetech thread](https://www.cemetech.net/forum/viewtopic.php?p=307057#307057) on a few issues with extant options for tokenization and some ideas for the future. In particular, having history-aware [de]tokenization is probably worth your trouble- there's a reason why the token sheets include the changes made to every token over the lifetime of this product line. The idea here is to take a calculator model and OS version and extract the token details for every token based on that information. Parsing these sheets is a hell of my own devising, and I'm willing to help you once my schedule clears. I'll get around to better documentation than 300 lines of Python code sooner rather than later, but it's designed to be [pretty easy for a relatively lazy XML parser](https://github.com/TI-Toolkit/tokens/blob/main/scripts/parse.py).

kg583 and Adriweb have done a lovely job ironing out the finer points TI-BASIC tokenization and have written efficient implementations which resolve many of the issues in this space. I particularly direct you towards [tivars_lib_py's implementation](https://github.com/TI-Toolkit/tivars_lib_py/tree/main/tivars/tokenizer), because you seem to be proficient in Python.

There's a few things going here. First, we "maximal-munch" (taking the longest possible token wherever possible) outside of strings. This is similar to what you're doing but it can be sped up significantly using a [prefix tree](https://en.wikipedia.org/wiki/Trie) data structure. Then, we use "minimal-munching" (taking the shortest possible token) when you are in a string. There's an exception for string arguments of `Send(`- this is all documented [here](https://github.com/TI-Toolkit/tivars_lib_py/blob/52c6871393d9d68c44642d0319885c59b5e14950/tivars/tokenizer/encoder.py#L16-L43). The motivations for these decisions are documented in my Cemetech post above.

---

This is a lot of complexity thrown at you all at once, and a significant amount of work, but I believe that matching the tokenization features of tivarslibpy would be an excellent future step for this project. Tokenization is a regular topic of discussion for us in the [TI-Toolkit](https://discord.gg/eqScMTRugz) and [Cemetech](https://discord.gg/EBrFCW8udA) Discord servers, and I'd love to chat there if you run into any problems!

**Comment by cqb13** [comment]
Thank you so much for your detailed feedback. Ill aim to to incorporate these suggestions.
